import "./globals.css";
import MyHeader from "@/components/header";
import MyFooter from "@/components/footer";
import { cookies } from "next/headers";
import MyHeaderLogout from "@/components/header-logout";


export const metadata = {
  title: "Signup with api call",
  description: "Generated by create next app",
};



export default async function RootLayout({ children }) {

  const cookiStore = await cookies()
  const cookie = cookiStore.get('accessToken')

  return (
    <html lang="en">
      <body>

        <div className="max-w-[780px] bg-white min-h-screen mx-auto p-4">
          {
            cookie ?
              <MyHeaderLogout />
              :
              <MyHeader />
          }

          {children}
          <MyFooter />
        </div>

      </body>
    </html>
  );
}
